# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Use the systemd-boot EFI boot loader.
  # boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot/efi";
  boot.loader.grub = {
    enable = true;
    device = "nodev";
   #  version = 2;  # depricated since 23.05
    efiSupport = true;
    gfxmodeEfi = "1920x1080";
    enableCryptodisk = true;
    copyKernels = true; # avoid boot errors if root is on zfs
  };
  boot.initrd = {
    luks.devices."root" = {
      device = "/dev/disk/by-uuid/5bfd24ab-5dd6-47f0-b715-b92e2681af85"; # UUID of LUKS container
      preLVM = true;
      keyFile = "/keyfile0.bin";
      allowDiscards = true;
    };
    secrets = {
      "keyfile0.bin" = "/etc/secrets/initrd/luks_keyfile_root.bin";
    };
    supportedFilesystems = [ "zfs" ]; # boot from zfs


  };
  boot.zfs.package = pkgs.zfs_unstable;
  # boot.zfs.enableUnstable = true; # enable module on newer kernels
  boot.supportedFilesystems = [ "zfs" ];
  
  #boot.kernelPackages = lib.mkForce config.boot.zfs.package.latestCompatibleLinuxPackages;
  boot.kernelPackages = pkgs.linuxPackages_6_11;
  
  #      options v4l2loopback exclusive_caps=1 video_nr=9 card_label=a7III



  networking.hostId = "9b206745"; # head -c4 /dev/urandom | od -A none -t x4
  networking.hostName = "p14s-dmo"; # Define your hostname.


  fileSystems."/" =
    { device = "rpool/safe/nixos-root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5d32ce9c-4750-478f-a6c4-b895e2736284";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/96A1-8620";
      fsType = "vfat";
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/d88963fe-d18d-4a4a-b8a7-52d9d25c9d53";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    { device = "rpool/local/nix-store";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/safe/home";
      fsType = "zfs";
    };

  fileSystems."/data" = 
    { device = "rpool/safe/home/data";
      fsType = "zfs";
    };

  swapDevices = [ ];

}
